GET http://localhost:5050/lists HTTP/1.1
Content-Type: application/json

######

GET http://localhost:5050/lists/64ac8b5b99161edf18d710f1 HTTP/1.1
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhdXJvcG9kaUBnbWFpbC5jb20iLCJpYXQiOjE2ODkwMzIyNzMsImV4cCI6MTY4OTExODY3M30.-eDKLMAQlCr345n8cbGjJTHbCFyZegHrAF1QwViUQFM

##########

POST http://localhost:5050/lists/new/64b080a0c100cf2aaac25aeb HTTP/1.1
Content-Type: application/json

{
    "title":"lista 3"
}

######

PATCH http://localhost:5050/lists/64a47499948577417695a823 HTTP/1.1
Content-Type: application/json

{
    "title":"Lista n.3"
}

######

DELETE http://localhost:5050/lists/delete/64a47499948577417695a823  HTTP/1.1