GET http://localhost:5050/lists HTTP/1.1
Content-Type: application/json

######

GET http://localhost:5050/lists/649df60123a29c0d08415a10 HTTP/1.1
Content-Type: application/json

##########

POST http://localhost:5050/lists/new/649df60123a29c0d08415a10 HTTP/1.1
Content-Type: application/json

{
    "title":"lista 9"
}

######

PATCH http://localhost:5050/lists/64a47499948577417695a823 HTTP/1.1
Content-Type: application/json

{
    "title":"Lista n.3"
}

######

DELETE http://localhost:5050/lists/delete/64a47499948577417695a823  HTTP/1.1