GET http://localhost:5050/products

########

GET http://localhost:5050/products/  HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhdXJvcG9kaUBnbWFpbC5jb20iLCJpYXQiOjE2ODkwMjk0OTksImV4cCI6MTY4OTExNTg5OX0.bSgFKgRKSNkKX6sUV6PHLnKm_YUUyuycslhsijs7WSU

#######

POST http://localhost:5050/products/new/64b19d687d42262081808cc8 HTTP/1.1
content-type: application/json

{
    "url" : "https://www.sephora.it/p/eaze-drop---fondotinta-opacizzante-P10014798.html",
    "img": "",
    "title": ""
}

########

GET http://localhost:5050/products/scraping/64b6b5ad85bdb3d30d7ddc27 HTTP/1.1
Content-Type: application/json

#######

DELETE http://localhost:5050/products/delete/64a4668263e5db39a0724d10 HTTP/1.1
