GET http://localhost:5050/users

###############

POST http://localhost:5050/users/new HTTP/1.1
content-type: application/json

{
    "firstName" : "Adriana",
    "lastName" : "Benedetti",
    "userName" : "Adria",
    "email" : "sauropodi@gmail.com",
    "password" : "Helloworld123!"
}

########

DELETE http://localhost:5050/users/delete/649df8b6e250c172a0c9ceb7 HTTP/1.1